
name: pipeline-aks
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select an Environment'
        type: choice
        required: true
        options:
        - staging
        - certification
        - production
      cluster:
        description: 'Select a cluster'
        type: choice
        required: true
        options:
        - control
        - rmc
        - csip
        - edge
      action: 
        description: 'Terraform action'
        type: choice
        required: true
        options:
        - Plan
        - Apply
        - Destroy
      debug:
        description: 'Debug Mode'
        default: false
        type: boolean
        required: false

jobs:
  initialize_runner:
    environment: ${{ github.event.inputs.environment }}
    runs-on: [self-hosted, nkrunner]
    outputs:
      runner_label: ${{ steps.set-runner.outputs.runner_label }}
    steps:
      - id: set-runner
        name: Set Runner Label
        shell: bash
        run: |
          echo "runner_label=self-hosted" >> $GITHUB_OUTPUT
          tree
